---
- name: 'Deploy 2 gcp vm with apache installed'
  hosts: localhost
  connection: local
  become: true
  gather_facts: no

  vars: 
    gcp_project: "project-wso2-training"
    gcp_cred_kind: "serviceaccount"
    gcp_cred_file: "service-account.json"
    gcp_region: "us-central1"
    gcp_zone: "us-central1-a"


  # Roles & Tasks
  tasks:

  - name: create a disk
    gcp_compute_disk:
      name: disk-instance
      size_gb: 30
      source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts
      zone: "{{ gcp_zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: disk

  - name: create a address
    gcp_compute_address:
      name: address-instance
      region: "{{ gcp_region }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: address

  - name: create a instance
    gcp_compute_instance:
      name: vm-instance
      project: "{{ gcp_project }}"
      zone: "{{ gcp_zone }}"
      machine_type: n1-standard-1
      disks:
        - auto_delete: 'true'
          boot: 'true'
          source: "{{ disk }}"
      labels:
        environment: testing
      network_interfaces:
        - access_configs:
          - name: External NAT
            nat_ip: "{{ address }}"
            type: ONE_TO_ONE_NAT
      tags:
        items:
        - http-server
        - https-server
      auth_kind: serviceaccount
      service_account_file: "{{ gcp_cred_file }}"
      state: present

  - name: install apache
    yum:
      name: apache2
      state: latest

  - name: start apache service
    service:
      name: apache2
      state: started
      enabled: true
  
  - name: copy index file
    copy:
      src: ./index.html
      dest: /var/www/html
    notify: restart apache2

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted   
